apiVersion: cert-manager.io/v1
 
kind: Certificate
metadata:
  name: fib.simplynull-tech-tls
spec:
  secretName: fib.simplynull-tech
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: fib.simplynull.tech
  dnsNames:
    - fib.simplynull.tech